[package]
name = "ssi-prototype"
version = "0.1.0"
authors = ["Michael Oultram <michaeloultram@users.noreply.github.com>"]

[dependencies]
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
statrs = "0.7.0"
