stages:
    - test

build:
    stage: test
    before_script:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2018-03-05
    script:
        - cd src/auto_parallelise
        - $HOME/.cargo/bin/cargo test --release

