stages:
    - build 
    - test

build:
    stage: build   
    before_script:
        - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2018-03-05
    script:
        - cd src/auto_parallelise
        - cargo build --release
test:
    stage: test  
    script:
        - cd src/auto_parallelise
        - cargo test --release

