[package]
name = "password-cracker"
version = "0.1.0"
authors = ["Michael Oultram <michael@oultr.am>"]

[dependencies]
auto-parallelise = { version = "0.1.0", path = "../../auto-parallelise"}
rust-crypto = "0.2.36"
time = "*"
