[package]
name = "fibinacci_array"
version = "0.1.0"
authors = ["Michael Oultram <michael@oultr.am>"]

[dependencies]
auto-parallelize = { version = "0.1.0", path = "../../auto-parallelize"}

[features]
default = []
