[package]
name = "fibinacci"
version = "0.1.0"
authors = ["Michael Oultram <michael@oultr.am>"]

[dependencies]
num_cpus = "*"
auto_parallelise = { version = "0.1.0", path = "../auto_parallelise"}

[features]
default = []
